spring.application.name=Final_Individual_Project

# ===============================
# PostgreSQL DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/training_db_java_final_project
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Disable H2 console (now unused)
# ===============================
spring.h2.console.enabled=false